// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: test/api/events.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *OrderCreateEvent) Reset() {
	*x = OrderCreateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_api_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateEvent) ProtoMessage() {}

func (x *OrderCreateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_test_api_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateEvent.ProtoReflect.Descriptor instead.
func (*OrderCreateEvent) Descriptor() ([]byte, []int) {
	return file_test_api_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreateEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderCreateEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OrderUpdateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *OrderUpdateEvent) Reset() {
	*x = OrderUpdateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_api_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdateEvent) ProtoMessage() {}

func (x *OrderUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_test_api_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdateEvent.ProtoReflect.Descriptor instead.
func (*OrderUpdateEvent) Descriptor() ([]byte, []int) {
	return file_test_api_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderUpdateEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderUpdateEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OrderDeleteEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *OrderDeleteEvent) Reset() {
	*x = OrderDeleteEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_api_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDeleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteEvent) ProtoMessage() {}

func (x *OrderDeleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_test_api_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteEvent.ProtoReflect.Descriptor instead.
func (*OrderDeleteEvent) Descriptor() ([]byte, []int) {
	return file_test_api_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDeleteEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderDeleteEvent_DeleteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *OrderDeleteEvent_DeleteInfo) Reset() {
	*x = OrderDeleteEvent_DeleteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_api_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDeleteEvent_DeleteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDeleteEvent_DeleteInfo) ProtoMessage() {}

func (x *OrderDeleteEvent_DeleteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_test_api_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDeleteEvent_DeleteInfo.ProtoReflect.Descriptor instead.
func (*OrderDeleteEvent_DeleteInfo) Descriptor() ([]byte, []int) {
	return file_test_api_events_proto_rawDescGZIP(), []int{2, 0}
}

func (x *OrderDeleteEvent_DeleteInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_test_api_events_proto protoreflect.FileDescriptor

var file_test_api_events_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x36, 0x0a, 0x10,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x10,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x1a, 0x20, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_api_events_proto_rawDescOnce sync.Once
	file_test_api_events_proto_rawDescData = file_test_api_events_proto_rawDesc
)

func file_test_api_events_proto_rawDescGZIP() []byte {
	file_test_api_events_proto_rawDescOnce.Do(func() {
		file_test_api_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_api_events_proto_rawDescData)
	})
	return file_test_api_events_proto_rawDescData
}

var file_test_api_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_api_events_proto_goTypes = []interface{}{
	(*OrderCreateEvent)(nil),            // 0: api.OrderCreateEvent
	(*OrderUpdateEvent)(nil),            // 1: api.OrderUpdateEvent
	(*OrderDeleteEvent)(nil),            // 2: api.OrderDeleteEvent
	(*OrderDeleteEvent_DeleteInfo)(nil), // 3: api.OrderDeleteEvent.DeleteInfo
}
var file_test_api_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_api_events_proto_init() }
func file_test_api_events_proto_init() {
	if File_test_api_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_api_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_api_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUpdateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_api_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDeleteEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_api_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDeleteEvent_DeleteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_api_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_api_events_proto_goTypes,
		DependencyIndexes: file_test_api_events_proto_depIdxs,
		MessageInfos:      file_test_api_events_proto_msgTypes,
	}.Build()
	File_test_api_events_proto = out.File
	file_test_api_events_proto_rawDesc = nil
	file_test_api_events_proto_goTypes = nil
	file_test_api_events_proto_depIdxs = nil
}
